export enum CounterActionTypes {
 INCREMENT = '@COUNTER/INCREMENT',
 INCREMENT_5 = '@COUNTER/INCREMENT_5',
 INCREMENT_10 = '@COUNTER/INCREMENT_10',
 DECREMENT = '@COUNTER/DECREMENT',
 DECREMENT_5 = '@COUNTER/DECREMENT_5',
 DECREMENT_10 = '@COUNTER/DECREMENT_10',
 RESET = '@COUNTER/RESET'
}
